server:
  port: 8003
eureka:
  instance:
    hostname: peer2
  client:
    register-with-eureka: true  #默认的eureka会将自己作为客户端来尝试注册自己  设置为false 代表不向自己注册
    fetch-registry: true         #由于注册中心的职责就是维护服务实例，它并不需要去检索服务， 所以也设置为 false。
    service-url:
      defaultZone: http://localhost:8002/eureka/