server:
  port: 8001
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  #默认的eureka会将自己作为客户端来尝试注册自己  设置为false 代表不向自己注册
    fetch-registry: false         #由于注册中心的职责就是维护服务实例，它并不需要去检索服务， 所以也设置为 false。
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #服务注册地址  并且还可以通过localhost:8001直接访问信息面板